# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586e15c09e14d2822520f380ebb825a1992eb7cb59f2ff6e05c1e6847f6594eac6864af56ee4028a0ac8f4debcae8ada1954a5fae2b518e1f44a8ac8f5ff1f3f

test:
  secret_key_base: 343697bd658c0191e5b19f217ccaeb77bd25c4538eb27da6a70908216ea05393f1125d320eb63953a9d22c934add93852efe6c168a89153dc9c4deb3d4866b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
